version: "3.8"
services:
  db:
    image: postgres:15
    container_name: notes-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: notes-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/notesdb?sslmode=disable
      JWT_SECRET: supersecret
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: notes-frontend
    depends_on:
      - backend
    environment:
      # When frontend runs inside Docker, use the backend service hostname so
      # the container can reach the backend over the Docker network.
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"

volumes:
  db_data:

